export interface PolicySection {
  id: string;
  title: string;
  paragraphs?: string[];
  bullets?: string[];
  subsections?: {
    title: string;
    paragraphs?: string[];
    bullets?: string[];
  }[];
}

export const cookiePolicyTitle =
  'Clarification Text on Processing Personal Data and Cookie Policy';

export const cookiePolicyIntro =
  'This Privacy Notice Regarding the Processing of Personal Data Retained by Keningford Partners LLC (hereinafter referred to as the "Company") has been specifically prepared with respect to the cookies used on this website.';

export const cookiePolicySections: PolicySection[] = [
  {
    id: 'why-notice',
    title: '1. Why Is This Notice Being Sent?',
    paragraphs: [
      'The General Data Protection Regulation (GDPR) replaced the Data Protection Act 1998 on 25 May 2018. The Company is now required to tell all data subjects about the data that is collected about them. This form may also be used to collect certain data.',
    ],
  },
  {
    id: 'subjects',
    title: '2. What Subjects Does This Notice Contain?',
    bullets: [
      'General information about cookies and cookies used on the website',
      'What data is being collected',
      'What purpose data is used for',
      'Whom the data is shared with',
      'The lawful basis for holding your data',
      'How long we will keep your data',
      'Your individual rights under GDPR',
    ],
  },
  {
    id: 'cookies-general',
    title: '3. General Information Regarding Cookies Used on the Website and Their Usage',
    subsections: [
      {
        title: 'Definition and Purpose of Cookies',
        paragraphs: [
          'Cookies, along with other tracking technologies such as pixels and gifs (hereinafter collectively referred to as "Cookies"), consist of small text files placed on users\' devices (e.g., tablets, mobile phones, or computers) or scripts running on their browsers during their use of online platforms such as websites or mobile applications.',
          'Cookies enable the servers of the Website and associated applications to recognize users\' devices, thereby facilitating functions such as managing website traffic and retaining user preferences, including language settings. Furthermore, Cookies allow for the analysis of visitor numbers and audience demographics, which aids in optimizing software performance and enhancing the user experience. Where explicit consent is provided, Cookies also enable the personalization of advertisements displayed during internet browsing activities.',
        ],
      },
      {
        title: 'Primary Purposes of Cookie Usage on the Website',
        paragraphs: ['The main objectives of utilizing Cookies on the Website include:'],
        bullets: [
          'Enhancing the functionality and performance of the Website to ensure the effective delivery of services to users;',
          'Improving the Website, implementing new features, and customizing the services provided in accordance with user preferences;',
          'Ensuring the legal and commercial security of the Website, its users, and the Company.',
        ],
      },
      {
        title: 'Classification of Cookies Based on Their Retention Periods',
        paragraphs: [
          'The Website utilizes the following categories of Cookies based on their duration of storage.',
        ],
      },
      {
        title: 'Cookies Generated by the Website and Third-Party Cookies',
        paragraphs: [
          'Cookies created and accessible exclusively by our Website are classified as first-party cookies. However, certain content offered on the Website may be provided through domain names other than the Website\'s primary domain name. In such cases, each respective domain generates its own third-party cookies.',
          'The categories of cookies utilized on the Website, along with their purposes, are detailed below:',
        ],
        bullets: [
          'Session Cookies: These cookies remain active only for the duration of the user\'s session on the Website and automatically expire upon the closure of the web browser.',
          'Persistent Cookies: These cookies are stored within the user\'s browser and remain valid either until deleted by the user or until the expiration date specified for the respective cookie. The data collected through these cookies cannot be processed for marketing purposes. If the use of such cookies is not permitted, certain functionalities or sections of the Website may become inaccessible.',
          'Strictly Necessary Cookies: These cookies are essential for the Website\'s proper operation and for users to access and benefit from the features and services offered. The data collected through these cookies cannot be processed for marketing purposes. If the use of such cookies is not permitted, certain functionalities or sections of the Website may become inaccessible.',
          'Functional and Analytical Cookies: These cookies are employed for the purpose of retaining user preferences, ensuring the effective operation of the Website, and optimizing the Website\'s performance in alignment with user requests. They collect data regarding user interactions with the Website and, by their nature, may include personal data. For instance, cookies that store the user\'s preferred language setting for the Website fall within the category of functional cookies.',
        ],
      },
      {
        title: 'Third-Party Cookies',
        paragraphs: [
          'The third-party cookies implemented on the Website aim to enhance user experience by providing a more efficient and functional online environment. In compliance with the applicable data protection legislation, a Data Protection Agreement has been executed between the Company and third-party service providers, ensuring that any personal data collected by these third parties on behalf of the Company is subject to appropriate security and confidentiality measures.',
        ],
      },
      {
        title: 'Additional Information About Cookies According to Their Parties',
        paragraphs: [
          'First-Party Cookies: These cookies are set by the website or domain that the user is directly interacting with. They are typically used to remember user preferences and provide a personalized browsing experience.',
          'Third-Party Cookies: These cookies are set by domains other than the one the user is currently visiting. They are commonly used for tracking user behavior across multiple websites for advertising, analytics, and other purposes.',
        ],
      },
      {
        title: 'Information About Cookies That Do Not Require Explicit Consent',
        bullets: [
          'User-Input Cookies: Used to remember user-entered information on a website, such as form submissions, login credentials, and preferences. Session-based cookies are deleted when the browser closes; persistent cookies may remain for a specified period. Use is disclosed through this notice and applicable data protection requirements.',
          'Authentication Cookies: Used to verify user identity during login and maintain authenticated sessions. Often session-based and deleted when the user logs out or closes the browser.',
          'User-Centric Security Cookies: Monitor and protect user-related activities to detect unauthorized access, fraudulent activity, and other security threats.',
          'Multimedia Player Session Cookies: Maintain player session state (preferences, playback progress, volume). Also known as "Flash cookies"; duration ends when the session terminates.',
          'Load Balancing Session Cookies: Distribute incoming traffic across servers and route subsequent requests consistently during a session.',
          'User Interface Personalization Cookies: Store layout, language, and interface preferences; validity may extend from a single session to weeks or months depending on purpose.',
          'Social Plugin Content Sharing Cookies: Enable liking, sharing, and commenting via embedded social plugins; should be session cookies unless "remember me" extends the session.',
          'Consent Management Platform (CMP) Cookies: Remember cookie consent preferences on pages visited.',
          'First-Party Analytical Cookies: Measure performance and user behavior using anonymous or aggregated data where possible.',
          'Cookies Used for Website Security: Essential to protect sessions, detect unauthorized activity, and maintain service availability.',
        ],
      },
    ],
  },
  {
    id: 'sharing',
    title: '5. With Whom and for What Purposes Do We Share Your Personal Data?',
    paragraphs: [
      'In accordance with the provisions of the General Data Protection Regulation (GDPR), we share your personal data in a manner that is lawful, fair, and transparent, ensuring its accuracy and up-to-date status. The data shared is strictly limited to specific, legitimate, and clearly defined purposes.',
      'Your personal data may be disclosed to public authorities, institutions, and organizations that are legally authorized to request such data for the purposes of resolving potential legal disputes, conducting investigations, or fulfilling judicial or administrative audits. Furthermore, your personal data may be shared in response to a legal obligation or other official or legal requests for information and documentation.',
      'Your personal data may also be shared with public authorities, courts, public prosecutors, enforcement offices, and other judicial authorities, as well as with legal advisers, as necessary to comply with legal and regulatory requirements, or when required to protect the legitimate interests of the Company in the context of litigation or other legal proceedings.',
    ],
  },
  {
    id: 'collection',
    title: '6. What Are the Methods of Collection and Processing of Your Data?',
    paragraphs: [
      'The Company automatically collects your personal data through cookies when you access this website. In the event of a dispute, the Company may process your data for the purpose of transferring it to the relevant authorities. The Company may also process your data by creating, storing, and maintaining databases, hosting, listing, filling out forms, drafting petitions, and completing other documents, either manually or through automated means, depending on the nature of the task and the type of personal data requested or required to be processed.',
    ],
  },
  {
    id: 'rights',
    title: '7. Your Rights Based on GDPR',
    bullets: [
      'Enable correction to data for accuracy.',
      'Request the deletion or removal of personal data where there is no compelling reason for its continued processing.',
      'Object to processing of personal data that is likely to cause, or is causing, damage or distress.',
      'Obtain and reuse your personal data for your own purposes across different services.',
      'Object to decisions being taken by automated means.',
      'In certain circumstances, have inaccurate personal data rectified, blocked, erased, or destroyed.',
      'Claim compensation for damages caused by breach of the data protection regulations.',
    ],
  },
  {
    id: 'browser-settings',
    title: '8. Cookie Settings from Browser Settings',
    paragraphs: [
      'You can customize your cookie preferences by clicking on the "Customize Cookie Settings (Cookie Management)" tab in the pop-up that appears during your first visit to our website. You can change your cookie preferences at any time by adjusting the buttons in the cookie management panel to the desired position (enabled or disabled) and clicking the "Save Settings" button.',
      'Additionally, you can partially control cookies through your browser settings. You can access information about managing cookies in popular browsers through the following links:',
    ],
    bullets: [
      'Google Chrome: https://support.google.com/accounts/answer/61416',
      'Mozilla Firefox: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop',
      'Microsoft Internet Explorer / Edge: https://support.microsoft.com/en-gb/windows/delete-and-manage-cookies',
      'Safari: https://help.apple.com/safari/mac/9.0/',
      'Opera: https://help.opera.com/en/latest/web-preferences/',
    ],
  },
  {
    id: 'precautions',
    title: '9. Precautions for Protecting Your Personal Data',
    paragraphs: [
      'Protection of personal data is an important issue for our company. Our company takes necessary technical and administrative measures to protect against unauthorized access to personal data or loss, misuse, disclosure, alteration, or destruction of this information. Our Company undertakes to keep your personal data confidential, to take all necessary technical and administrative measures, and to take the necessary care to ensure confidentiality and security.',
      'Although our company has taken the necessary information security measures, if personal data is damaged as a result of attacks on the website and the system or is received by third parties, our Company will immediately notify you and the relevant data protection authority.',
    ],
  },
  {
    id: 'accuracy',
    title: '10. Accuracy and Up-to-Date Storage of Your Personal Data',
    paragraphs: [
      'By sharing their personal data with us, individuals acknowledge and expressly declare that the information provided is accurate and current, and that they are aware of the importance of maintaining the accuracy and up-to-date status of their personal data in relation to the rights granted to them under the General Data Protection Regulation (GDPR).',
      'Any amendments and/or updates to your personal data may be communicated to us via the physical address provided below, electronic mail address, or through the email address specified on this website.',
    ],
  },
  {
    id: 'deletion',
    title: '11. Deletion, Destruction, or Anonymization of Your Personal Data',
    paragraphs: [
      'Personal data processed for the purposes set forth in this notice shall, when the purpose for processing ceases to exist and upon the expiration of any retention periods prescribed by applicable laws, be deleted, destroyed, or anonymized in accordance with the Company\'s Personal Data Retention and Destruction Policy. Such actions shall be carried out either automatically or upon your request, and any anonymized data may continue to be used in accordance with the applicable legal provisions.',
    ],
  },
  {
    id: 'controller',
    title: '12. Data Controller',
    paragraphs: [
      'Keningford Partners LLC',
      'Address: 8 The Green Suite B in the City of Dover, Delaware, United States of America',
      'This Cookie Policy issued by our Company may be periodically updated to reflect our personal data practices. In the event of significant changes to this Cookie Policy, notifications will be provided, particularly through our website.',
    ],
  },
];
